### PR TITLE
Update translation_de.ts

### PR DESCRIPTION
**Pull request by ghost**
Please don't merge, this is unfinished. I'll add more translations soon.

### CODE REVIEW

**Comment by ghost** [comment]
I can't translate this right because I don't know what it does/means. Can somebody explain it to me?
 ```
<message>
        <location filename="bootselectiondialog.ui" line="38"/>
        <source>Sticky default</source>
        <translation type="unfinished"></translation>
</message>
```

**Comment by procount** [comment]
It it the title/description for the checkboxes to the left of each OS name.
Only 1 checkbox can be selected at any time to make that the DEFAULT OS that will be booted by PINN in the absence of any other user interaction.
But the user may select another OS to temproraily boot for this time only. On the next boot, PINN will again boot the OS that is marked as the default (without any user interaction).
Therefore this setting is "STICKY" because PINN keeps coming back to this OS as the default OS to boot.
I hope that makes sense?

**Comment by ghost** [comment]
Yes. Thank you.

**Comment by procount** [comment]
Sorry, I was in the middle of updating. Please check your translations against the latest commit.
Then let me know when you have finished all of your updates.

**Comment by procount** [comment]
I have manually merged your changes so far.
Due to the pending commits. I'm going to close this PR as complete. Please create another for further updates.
Thanks

**Pull request closed without merging**
