### PR TITLE
Add some French translations and fix some mistakes

### PR DESCRIPTION
**Pull request by Jey2k**

### CODE REVIEW

**Comment by procount** [comment]
Thanks

**Comment by Jey2k** [comment]
my pleasure...  It lets you concentrate on a downloaded flavour feature ;)

2017-12-06 0:00 GMT+01:00 procount <notifications@github.com>:

**Comment by procount** [comment]
merged

**Comment by procount** [comment]
Dear PINN Translator!
I have pushed up next the set of translation files to github ahead of the next release of PINN.
If you are willing, I would appreciate it if you could translate the new messages so that they can already be included when I release the next version of PINN.
Many thanks,

**Pull request closed without merging**
