### PR TITLE
Update Italian language

### PR DESCRIPTION
**Pull request by bovirus**
Please check strange not blank space on line 1741/1781/1844
Please check string     <message utf8="true"> on line 1738

because are not qt standard and can create problem editing file with QTLinguist (that convert them).

Just try to open your original file (translation_it.ts) with QTLinguist and save it with another name and compare two files.

### CODE REVIEW

**Comment by procount** [comment]
Thanks I'll take a look.

**Comment by bovirus** [comment]
@procount

Please merge my proposal of language update.

About strange spaces I checked that in hex format this strange space instead 20 (space) is a double char C2A0.

I found the same chars in English and other languages.

**Comment by procount** [comment]
> Just try to open your original file (translation_it.ts) with QTLinguist and save it with another name and compare two files.

I tried this, but I saw no difference.
I'm guessing I must have cut & pasted some strange "non-blank" space from the documentation into the code, but I can't find it at the moment. I might have to retype it in the code and re-extract the ts files to avoid it coming back again.

**Comment by procount** [comment]
OK, I think I see the problem.

**Comment by procount** [comment]
I think there are still some things to fix in it, but is the version I just released good enough for now?

**Comment by procount** [comment]
> About strange spaces I checked that in hex format this strange space instead 20 (space) is a double char C2A0.

It was actually a back-tick that I had pasted in from the documentation, but QT obviously converted it to something else that looked like a space, but wasn't.

**Comment by bovirus** [comment]
@procount 

Please check these two .ts files in zip archive

Your original file
Same file open by QT Linguist 5.12.4 and saved (no changes in text)

[recovery_it.zip](https://github.com/procount/pinn/files/3337632/recovery_it.zip)

make a compare and you will find that strange space are converted as &#xa0;

**Comment by lurch** [comment]
@procount Is this similar to https://github.com/procount/pinn/pull/252 ? I suspect some of the source-code files (accidentally) have a non-breaking space in them (as opposed to a regular space), and this is making QT Linguist get "confused" somewhere along the way. And you can't "see" them because any UTF-8 compliant editor will probably display a non-breaking space identically to a breaking-space?
You might need to resort to using a hex-editor to see (and edit) the actual underlying bytes and replace non-breaking space characters (the C2A0 that @bovirus mentions) with regular space characters? :confused:

**Comment by bovirus** [comment]
@lurch 

I can confirm that it's the same problem.
The line mention in post 252 it's the same and there are other liens with a similar problem.

@procount 
Please replace in source code/source strings all non-breaking space with standard space.

**Comment by procount** [comment]
Are they still there in the latest commit? I thought I had removed them all?

Mind you I have bigger problems at the moment as I'm getting a kernel panic on latest dev build for some reason.... Still recovering from aftermath of pi4 split kernels I think!

**Comment by bovirus** [comment]
NO problem.
Just check here https://github.com/procount/pinn/issues/273
Please fix when you can.

**Comment by lurch** [comment]
@procount there still seems to be quite a few lurking around... try running this in the root of the repo:
```bash
find recovery/ -name "*.h" -o -name "*.cpp" -o -name "*.ui" -o -name "*.ts" -exec hexdump -C {} \; | grep 'c2 a0'
```

Good luck with fixing your kernel panics :crossed_fingers:

**Comment by bovirus** [comment]
@procount 

The files that seems containes non-breakable spaces are:

recovery\optionsdialog.ui
recovery\translation_ae.ts
recovery\translation_ast.ts
recovery\translation_ca.ts
recovery\translation_de.ts
recovery\translation_en.ts
recovery\translation_es.ts
recovery\translation_eu.ts
recovery\translation_fi.ts
recovery\translation_fr.ts
recovery\translation_hu.ts
recovery\translation_it.ts
recovery\translation_ja.ts
recovery\translation_ko.ts
recovery\translation_nl.ts
recovery\translation_no.ts
recovery\translation_pl.ts
recovery\translation_pt.ts
recovery\translation_ru.ts
recovery\translation_sv.ts
recovery\translation_tr.ts
recovery\translation_zh_TW.ts

**Comment by procount** [comment]
All the .ts files get generated automatically from the source files.
The recovery/optionsdialog.ui is the source of all the problems and is where they need to be fixed.

However, the .ts files contain \<oldsource\> entries which the linguist docs say is the result of a merge.
So even if optionsdialog.ui is fixed and propagates through to the \<source\> entries, I wonder if the \<oldsource\> entries may still contain the bad characters? I don't know if it is safe to just delete them? Maybe I will try.

**Comment by bovirus** [comment]
@procount 

I propose to you to fix the problem in recovery\optionsdialog.ui then we can check.

I propose a PR with changes in optiondialog.ui

https://github.com/procount/pinn/pull/275

**Comment by bovirus** [comment]
@procount

Could you please merge this update for Italian language and close the PR?

**Comment by procount** [comment]
Please check latest commit.

**Comment by procount** [comment]
Hopefully this is all merged and fixed now.

**Pull request closed without merging**
