### PR TITLE
update openssl to 1.1.1l

### PR DESCRIPTION
**Pull request by matthuisman**
give this a go?

### CODE REVIEW

**Comment by procount** [comment]
Oh the irony! - buildroot wouldn't pull down the new version of openssl due to a certificate error.... So I had to do it manually.
But then it doesn't play nicely with QT.

**Comment by lurch** [comment]
> Oh the irony! - buildroot wouldn't pull down the new version of openssl due to a certificate error.... 

:rofl: 

> But then it doesn't play nicely with QT.

:cry: 
Is NOOBS also affected by this issue, or is NOOBS just "lucky" in that none of the HTTPS sites it uses are using a cert from LetsEncrypt?

**Comment by procount** [comment]
Yes, NOOBS is affected for Lakka and Recalbox, probably because they are externally hosted. I have made Xecdesign aware.

**Comment by lurch** [comment]
I believe XECDesign is pretty busy with Bullseye at the moment...

**Comment by procount** [comment]
Yes I know. And NOOBS is going to be pretty low on the priority list too.

**Comment by matthuisman** [comment]
@procount 
did you see this?
https://www.openssl.org/blog/blog/2021/09/13/LetsEncryptRootCertExpire/
Any of those options possible for PINN?
reading more, looks like option1 would be the only possiblity.

sounds like QT may only work with 1.0.2 openssl api?

**Could you try with this PR and enable libressl instead of openssl?**
"LibreSSL is API compatible with OpenSSL 1.0.1, but does not yet include all new APIs from OpenSSL 1.0.2 and later. LibreSSL also includes APIs not yet present in OpenSSL. The current common API subset is OpenSSL 1.0.1."

**Comment by matthuisman** [comment]
see my new PR here: https://github.com/procount/pinn/pull/564

**Pull request closed without merging**
