### PR TITLE
Update Italian translation

### PR DESCRIPTION
**Pull request by bovirus**
@procount 

Update Italian translation

- Problem pending on source English strings

There are several source strings with same problems.

If a string that has multi-period please separate each period with a new line.
It help readibility.

If a string it's multiperiod with "." at th end of first period the string have to end with "." on last period.

There are several interruptable space instead simple space.
Please change all interruptable space with normal space.

Example for both problem

    <message>
        <location filename="initdrivethread.cpp" line="217"/>
        <source>SD card has now been formatted ready for PINN installation. 
Please re-copy the PINN files onto the card and reboot.</source>
        <oldsource>SD card has now been formatted ready for NOOBS installation. 
Please re-copy the NOOBS files onto the card and reboot</oldsource>
        <translation>La scheda SD è stata formattata ed è pronta per l&apos;installazione di PINN. 
Ricopia i file PINN nella scheda SD e riavvia.</translation>
    </message>

### CODE REVIEW

**Comment by procount** [comment]
I will check again. I thought I had removed all the non-interruptible spaces.
Sorry, I'm not very consistent with my periods, and many just got copy-pasted from the README_PINN.MD. I'm surprised @Lurch hasn't picked me up on more of them! (maybe there were too many of them) :wink:

**Comment by procount** [comment]
I'm a bit unsure how to handle shortcut keys in an internationalisation sense.
I think Qt takes care of changing the shortcut key if a translator changes it in the resource file.
But the way I coded the CEC TV remotes is that it simulates pressing the original shortcut key, not the translated one, so I think that changing the shortcut keys may cause a problem.
So I'm open to advice on that one. @Lurch - you have translation experience - any advice?

**Comment by bovirus** [comment]
@procount

Please take care about my note and for this moment merge my language.
You will check about my note in new release.

**Comment by procount** [comment]
I have just merged your patch, rebuilt, updated the TS files and pushed to github.
There is a test version of the PINN binary in https://sourceforge.net/projects/pinn/files/testing/ called pinn-322a.zip that you can try out.

**Pull request closed without merging**
