### PR TITLE
Create license

### PR DESCRIPTION
**Pull request by bobbbay**
An MIT license will be added to the project.

### CODE REVIEW

**Comment by procount** [comment]
There is already a license in recovery/license.txt

**Comment by bobbbay** [comment]
Github still thinks that there isn't a LICENSE on it because it isn't in Gihub's known location. Maybe moving the license to somewhere github can see it? Just a thought, that's all.

**Comment by procount** [comment]
Rightly or wrongly, this is a fork of NOOBS, so I follow the licensing requirements of NOOBS.

**Comment by lurch** [comment]
Related discussion in https://github.com/raspberrypi/noobs/pull/561

**Pull request closed without merging**
