### PR TITLE
Update of Italian language

### PR DESCRIPTION
**Pull request by bovirus**
@procount 

Please check and merge.
Thanks.

### CODE REVIEW

**Comment by procount** [comment]
You are so "on the ball" ;) Thanks,

**Comment by bovirus** [comment]
@procount 

Sorry why didn't you merge it?

**Comment by procount** [comment]
I have done, but only locally so far, I need to push it up. I was just contemplating whether to push it on its own, or to include some other changes, that's all. Been very busy lately,
If it is urgent, I can push it up sooner.
Many thanks.

**Comment by procount** [comment]
merged.

**Pull request closed without merging**
