### PR TITLE
Add Basque translation

### PR DESCRIPTION
**Pull request by aldatsa**

### CODE REVIEW

**Comment by bovirus** [comment]
@aldatsa 
Thanks for the update.
Please take care that you should change also recovery/recovery.pro to ad translate_eu.ts to the project.
Could you help me to post all language files as pull request?
Could you write just few steps how to do it?

**Comment by aldatsa** [comment]
@bovirus Thank you very much, I didn't notice that.

Looking at your github account I think that you know the basics of git and github, and you have created some pull requests correctly, for example:
https://github.com/raspberrypi/noobs/pull/362
https://github.com/opengapps/opengapps-app-support/pull/29

I don't understand. I can create the pull requests if you want but I think you are capable of doing it yourself.

EDIT: I have just noticed that you created the pull requests (#12 and #13). Nice!

**Comment by bovirus** [comment]
@aldatsa 

Just I wrote the message I tried to rember how did it in the past and I "hope" to do it now well (I made theese operation so few times..).

**Comment by procount** [comment]
Incorporated into trans2 branch

**Pull request closed without merging**
