### PR TITLE
Update Italian language

### PR DESCRIPTION
**Pull request by bovirus**
@procount 

Please check and merge

### CODE REVIEW

**Comment by bovirus** [comment]
@procount 

Could you please check and merge? Thanks.

**Comment by procount** [comment]
Sorry, been really busy, but next version should be released pretty soon now.

**Comment by bovirus** [comment]
@procount 

My request is not about to release but to merge the file. Thanks.

**Comment by procount** [comment]
Please help me understand why this is important to you.
The GitHub repo is normally updated after I make a release to reflect the contents of the last release. It is not normally in advance of a release. I don't build from that repo but from an internal one.

**Comment by bovirus** [comment]
@procount

Update the language that didn't means make a new release.

If you make all jobs in a second time there are more risks to forget something.
I didn't udnerstand because make all chanegs in a queue to do after.
github help to make this changes steps by steps.

If you merge now the language changes you don't have to remind to do it after.

**Comment by procount** [comment]
Ah ok, so you're just making sure it is integrated.
Normally I merge your PR into my local branch straight away so that it is captured.
Then when I release the next version, the github repo gets updated. So there tends to be a lag in reporting.
If I merge your change directly into the github repo, it could be lost next time I update from my local repo.

So in future I will try to mark it as merged when I merge it into my local git repo so you know it has bene done.
Would that be better for you?

By the way - thanks for all your continued support on the translations. It is much appreciated.

**Comment by procount** [comment]
Merged locally

**Pull request closed without merging**
