### PR TITLE
Update Translation for Korean

### PR DESCRIPTION
**Pull request by sople1**
recovery/translation_ko.ts
- change Korean words, paragraph

buildroot/package/arora/arora.mk
- edit Arora version (for Korean language)

recovery/mainwindow.cpp
- enable Korean language for Arora
    - (cause by, old version of Arora not have Korean language before)

### CODE REVIEW

**Comment by procount** [comment]
Hi Sople1,
I have updated Arora for the next version from your PR
I have moved on quite a bit since the last release, so I am wondering if your translations will still be valid and how I could incorporate them...? So, perhaps you can wait until after the next release and retranslate that instead? Hopefully it will not be too long away.

**Comment by sople1** [comment]
Ok. Please remind me when your work is completed. Thanks.

**Comment by procount** [comment]
A new version of PINN has been released.

**Comment by procount** [comment]
merged

**Comment by sople1** [comment]
Oh, thanks for your work.
I have been busy with quitting company that I worked in the last month. T.T

**Comment by procount** [comment]
Sorry to hear that. Hope you've got somewhere better to go to.
Your translations I merged were for the previous version, but hopefully by merging them now it will make the next set easier as it avoids you having to redo them except where I already changed the text.
Thanks for your translation support.

**Comment by procount** [comment]
Dear PINN Translator!
I have pushed up next the set of translation files to github ahead of the next release of PINN.
If you are willing, I would appreciate it if you could translate the new messages so that they can already be included when I release the next version of PINN.
Many thanks,

**Pull request closed without merging**
