### PR TITLE
Update Italian translation

### PR DESCRIPTION
**Pull request by bovirus**

### CODE REVIEW

**Comment by bovirus** [comment]
@procount 

Did you merge nmy translation update?

**Comment by procount** [comment]
I merged #168 and pushed it up. AFAICT, in this PR you just removed 3 "unfinished" attributes. So I've merged them locally but not pushed yet. Does that make a difference? I was going to wait til my next release.
EDIT: Neither are in the released version of PINN yet, just in the source.

**Comment by bovirus** [comment]
@procount 
You should remove unfinished attribute otherwise the translation is in place but in QT Linguist Editor the transation has yellow tick (translated but not checked) and is not used as it was untranslated.
Only removing unfinished attributes the tick is green and it marked as completed translation.

**Comment by procount** [comment]
Ah ok. I've updated github now. Is that better?

**Comment by bovirus** [comment]
@procount 
Now the Italian translation is OK (fully translated).
The are some small things I believe to fix in ZH_TW translation.

@s8321414 
Please check your ZH_TW translation
There are three strings marked in yellow in QT Linguist.
The problem is the end character (. or space) that is missing in your translation.
If you check original and respect the same end character you can get also green tick on it.
Is not unfinished strings. 
Is only strings marked with end punctation warning. But tehs trings are used in the translation.

**Comment by procount** [comment]
@bovirus - Are you sure zh_TW is still affected? I can't find any unfinished attributes in it.

**Comment by bovirus** [comment]
@procount 

The report about ZH_TW is a different problem.
Are not unfinished strings. Are string with warning for end punctation.
But are used in language file.
It's different then problem that I posted about unfinished attribute in italian language.

**Pull request closed without merging**
