### PR TITLE
Fix cert errors

### PR DESCRIPTION
**Pull request by AaronDewes**
Port of raspberrypi/noobs#604

### CODE REVIEW

**Comment by procount** [comment]
Merged locally. Thanks

**Comment by AaronDewes** [comment]
@procount Sorry, I forgot a few things, force-pushed now.

**Comment by procount** [comment]
There's a small error in Config.in, but I fixed it.
How can I tell it is working? I mean where can I find the previous cert errors and see that they are now absent?

**Comment by AaronDewes** [comment]
It happened to me when visiting any website using arora, like google.com, github.com, ...

**Comment by procount** [comment]
I never saw any errors with these sites, so difficult for me to check, but this new PR doesn't seem to break anything.

**Pull request closed without merging**
