### PR TITLE
Update zh_TW translations.

### PR DESCRIPTION
**Pull request by s8321414**
I updated zh_TW translations, please review and merge it :smiley:

### CODE REVIEW

**Comment by bovirus** [comment]
@s8321414 

Please open the file with QTLinguist

Then please check the icon on the cleft if you have

- red exlamation mark 
typically cpuld be a space start as start that didn't match with source (avaialable or not)
typically cpuld be a "." that didn't match with source (avaialable or not)

- yellow tick
String OK but not confirmed.

Please check on bottom right that at the end you should have 475/475 (all strings translated and checked) and on the left all green tick (no string mismatch).

**Comment by procount** [comment]
I saw only 1 yellow tick, which is not an error, so I merged it.
Thanks.

**Comment by bovirus** [comment]
@s8321414

Please check your translation with QTLinguist.

There is an yellow tick about thsi source string

Please accept these T&Cs to continue.

because in the trasnaltion seems that the accelerator (&C) is missing.

**Comment by lurch** [comment]
> Please accept these T&Cs to continue.
because in the trasnaltion seems that the accelerator (&C) is missing.

In that case, &C isn't actually an accelerator, but "T&Cs" in English is a common shorthand for "Terms and Conditions".
@procount Is there any way to mark that &C there _isn't_ an accelerator (shortcut key)? Or maybe it's worth rewording that phrase, so it'll be easier for translators to translate?

**Comment by procount** [comment]
Dunno.
Maybe I could insert spaces as in ' T & Cs' ?

**Comment by bovirus** [comment]
Yes could do it.

Please check here.

https://github.com/procount/pinn/issues/284

There is another fix request (/. at teh end of string).

**Comment by procount** [comment]
done & updated IT and ZH_TW

**Comment by bovirus** [comment]
@procount 

Please close this PR.

**Pull request closed without merging**
