### PR TITLE
Update translation_de.ts

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
I don't know why GitHub shows the diff like that, but the files are the same, I only added some translations.

**Comment by bovirus** [comment]
@RaspberryPiFan 

Please check the de language file with QTLinguist (if you want I can provide this program).

You have 303 of 457 strings translated (154 strings not translated).
Please if you can complete all strings not translated.

Please check with QT Linguist

Yellow question mark - Strings with syntax errors like end point different then source
Red exclamation mark - Problems on parameter like %1

**Comment by procount** [comment]
You may also want to wait until @lurch has updated the source strings to use parameters better. Then it will be easier to translate them.

**Comment by ghost** [comment]
@bovirus I use Virtaal to translate, it can do the same.

**Comment by bovirus** [comment]
@RaspberryPiFan 

I checked and seems that Virtaal didn't make the same check of QT Linguist.
Virtaal is quite old project (2012) that just compare source/translation as text without many additional checks.
For me Virtaal could be easy but is not suggested if you want make additional checks.

QT Linguist make a l lot of check on translation consistency.

Please try to open your language file with QT Linguist and check yellow question mark/red exclamation mark.

Please complete the translation and check translation consistency.

**Comment by lurch** [comment]
> I don't know why GitHub shows the diff like that

I suspect that might be because the line-endings have changed from Unix->DOS or vice-versa?

**Comment by ghost** [comment]
Okay, I'm re-translating this with QT linguist

**Pull request closed without merging**
