### PR TITLE
Update optiondialog.ui

### PR DESCRIPTION
**Pull request by bovirus**
Replace unbreakable space with standard space

### CODE REVIEW

**Comment by procount** [comment]
👍 Thanks. I thought I had done those already. Maybe I forgot to save.

**Comment by bovirus** [comment]
@procount 

If you merge this change and re-run the creation of .ts langauge files we can check if it's right now.

**Comment by procount** [comment]
Will do. Might be a little while, whilst I sort out the kernel panic.

**Comment by lurch** [comment]
https://www.youtube.com/watch?v=nR0lOtdvqyg
:wink:

**Comment by bovirus** [comment]
@procount

Could you please merge this fix and close the PR?

**Comment by procount** [comment]
Please check latest commit.

**Comment by procount** [comment]
Hopefully this is all merged and fixed now.

**Pull request closed without merging**
