### PR TITLE
Removed unneeded if

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by lurch** [comment]
This change was originally made in https://github.com/procount/pinn/commit/1bc287ca7ff3c7ffd18e1105eb6913d61285d66c#diff-224b76311c90ec3c0f6754f671e0e10d

@procount Is there more "dead code" that can be removed here too?

**Comment by procount** [comment]
This change was transitional for building across "various" repos for the Pi4. I prefer to leave it in as a placemarker for the future...

**Comment by ghost** [comment]
Ok. Should I close this PR?

**Comment by procount** [comment]
Yes you can, because I don't think I will be using it. Feel free to use it yourself, but in the scheme of things, I don't think it makes much difference.

**Pull request closed without merging**
