### PR TITLE
Add runCustomScript(), add rpi-backlight driver...

### PR DESCRIPTION
**Pull request by phmio**
Hi @procount 
runCustomScript() runs your background.sh at startup and before-reboot.sh just before soft reboot of selected OS to add some stuff like setting brightness or power off display & co.
rpi-backlight driver added with make_arch_linux-menuconfig.sh (kernelconfig-recovery-armv6/7), and also
fix resizing content of bootselectiondialog...
Be indulgent because it is my first time on git and my first pull request :wink:

### CODE REVIEW

**Comment by procount** [comment]
Thanks for the PR. I will take a look.
Don't expect it all to be integrated as is, because I have solved some issues already for the next release which I am currently testing. So I may need to modify some aspects to integrate into the new structure.

**Comment by phmio** [comment]
Ok thanks.

**Comment by procount** [comment]
I don't understand the purpose of running the script just before a "soft" reboot to set backlight brightness etc.  Surely anything set here will be lost after the reboot? If you are trying to modify the OS that has just been installed to set the brightness on its first boot, for example, then the partition_setup.sh script or using noobsconfig aspects might be better suited.

**Comment by phmio** [comment]
I use `before-reboot.sh` to power off the touchscreen at the PINN side because when i boot a selected  OS that forces the use of TV/HDMI display by disabling the touchscreen with `ignore_lcd=1`(config.txt), the touchscreen stays like that:
white_lines_ugly

And as i don't want or could not modify the content of the root OS partition (eg. Openelec v6.03 which loads the read only squashfs root file SYSTEM at boot and also don't include the backlight drivers) , i needed to do it that way.

I 'am not aware of partition_setup.sh and the noosconfig tools... I've been looking at it quickly but i think that when the OS to install loads it own root system as read only file like squashfs it must be more complicated to customize, but maybe i wrong.

Here is my multi-boot example:
- OpenElec (TV)
- OpenElec (LCD DSI)

In fact i have not used PINN in a normal way, to make my multi-boot i have just created 3 partitions with gparted. Two small partitions each containing the Openelec boot files (one disables the LCD touchscreen and the other leaves the default LCD enabled).
Those 2 partitions all point to the 3rd partition that contains the Openelec root files.
Example of before-reboot.sh:
`if [ -f /sys/class/backlight/rpi_backlight/bl_power ]; then echo 1 > /sys/class/backlight/rpi_backlight/bl_power ; fi`

**Comment by procount** [comment]
Ok I can add that as well. 
Would it matter if both scripts ran detached?
Almost ready for next major release so I'll be able to include this.

**Comment by phmio** [comment]
I think that `before-reboot.sh` should be run synchronously not detached, because we have to be sure that it runs and finishes before the reboot starts (`reboot(RB_AUTOBOOT)`).

**Comment by procount** [comment]
Included in p2.4.3

**Pull request closed without merging**
