### PR TITLE
Update translation_ko.ts

### PR DESCRIPTION
**Pull request by sople1**
I think that string was on translation... TT

Thanks for your work. :)

### CODE REVIEW

**Comment by procount** [comment]
I fixed this for you already in latest commit. https://github.com/procount/pinn/pull/293#issuecomment-510542406

**Comment by sople1** [comment]
Thanks for it :D

**Comment by bovirus** [comment]
@sople1 

Why so many strings in your translation has "." at the end of strings when "." is not present in source strings?

Is it a special requirement of your language?

**Comment by lurch** [comment]
> Is it a special requirement of your language?

Explained in https://github.com/procount/pinn/pull/292#issuecomment-510529428 ?

**Pull request closed without merging**
