### PR TITLE
Update Korean language (QT yellow tick fix)

### PR DESCRIPTION
**Pull request by bovirus**

### CODE REVIEW

**Comment by lurch** [comment]
Ping @sople1 
IMHO (and hopefully @procount agrees) it's more important for a native Korean speaker to be happy with the translations, than it is to worry about any "yellow ticks" that the QT tools might display.

**Comment by procount** [comment]
I don't think this is an error. Probably my mistake by using an & that is not used as an accelerator. But linguist doesn't know that.

**Comment by bovirus** [comment]
@lurch 
Infact I didn't tocuh teh strings.
Because I didn't have the knlowdge to do that.
I check that there are some misunderstanding ik KO translation about start space, end punctation, etc, Then I'm concentarte on this.
Because a yellow tick it's a warning but you are not always sure that it's just a warning if you don't check.
And then it mean that you have to check for each update,

**Comment by sople1** [comment]
@bovirus 

Korean is not latin-style language.
Belows are examples...
- some translations sentences are allowed if no tailing ".", but that is not correct on Korean language.
> recovery/translation_ko.ts:9
>     (동기화) 기록을 완료합니다
> same as tailing "~니다" are "saying" sentences, so that will be tailing "." 

- some translation sentences are not correct tailing "?"
> recovery/translation_ko.ts:43
>     : 디스크 용량이 가득 찬 것 같습니다?
> same as tailing "~니까" /  "~까요" are "question" sentences, so that will be tailing "?".
> but this sentence should be "notice" on Korean.

- some translation sentences are not good at including replaceable variables.
> recovery/translation_ko.ts:2448
>   파티션을 복사하고 있습니다  %d / %d ...
> no, if it to be edit, %d(second) 개 중  %d(first) 번 파티션을 복사하고 있습니다...
> strictly, "..." is not correct ending because "……" is correct... oh, more strictly, all dots should be middle-center. cause by difficult on typing, users use "..." typically. so tailing "..." must not to be break with "~니다"

Some strings are difficult tings for changing vocabulary order for Koreans. Cause by I selected to using current format, some sentences are having somethings. etc) space...
Some strings will be explain more for using, so I add some unnoticed words for it.

Well, although these condition, should you want to match all of punctuation?

**Comment by bovirus** [comment]
@sople1

Thanks Then it's better to leave your language untouched.

It mean that every time will be change somethings in soure code for translation you should have check all yellow tick to show the differences and check if you have to edit somethings.

Use QT Linguist and disable end pucattion check to disable all yellow tick about it.

@procount 

Please reject this PR.

**Comment by sople1** [comment]
@bovirus

Thanks for your understand.
Maybe it will be similar on Chinese, Japanese (more: Japanese uses not dot "." but circled dot "。")

**Comment by bovirus** [comment]
@procount 

Please close this PR.

**Pull request closed without merging**
